# Paths
pretrained_model_name_or_path = "runwayml/stable-diffusion-v1-5"
train_data_dir = "F:/Dev/LoRA-Training/tagger/final"
output_dir = "F:/Dev/LoRA-Output"
output_name = "Ava_LoRA_v1"

# LoRA Settings
network_module = "networks.lora"
network_dim = 128
network_alpha = 64
save_model_as = "safetensors"

# Training Parameters
resolution = "768,768"
train_batch_size = 2
max_train_steps = 4000
learning_rate = 0.0001
optimizer_type = "AdamW8bit"
lr_scheduler = "cosine"
lr_warmup_steps = 0
gradient_accumulation_steps = 1
mixed_precision = "fp16"
xformers = true

# Captions
caption_extension = ".txt"
shuffle_caption = true
