import os

# === CONFIG ===
IMAGES_DIR = r"F:\Dev\LoRA-Training\tagger\final"  # Change this to your folder with the 166 images

# === CAPTIONS POOL (166 unique captions) ===
CAPTIONS = [
    # Neutral Descriptive Variations
    "Extremely fat woman with a huge belly, wide hips, thick thighs, and soft arms.",
    "Massive soft body with a hanging belly, wide hips, and heavy breasts.",
    "Obese figure with a round gut pooling forward, fat arms, and plush thighs.",
    "Thick-bodied woman with sagging belly folds and big breasts resting above.",
    "Overweight woman with a belly draping over thighs, arms soft and heavy.",
    "Large obese frame with a protruding gut and full curvy thighs.",
    "Super thick female figure with wide hips, rounded belly, and heavy chest.",
    "Very obese body with belly folds pressing downward and plush limbs.",
    "Immense soft figure with hanging belly rolls and a broad heavy torso.",
    "Wide-hipped fat woman with an oversized belly and thick thighs.",
    "Heavily overweight figure with gut pressing forward over hips and thighs.",
    "Soft fat body with deep belly creases and plump arms.",
    "Plus-size figure with a heavy stomach sagging low onto legs.",
    "Large round belly resting low, wide hips supporting heavy curves.",
    "Thick soft figure with sagging stomach folds pooling forward.",
    "Massive body with belly rolling downward and thick plush thighs.",
    "Heavyset female with gut folds pressed deep into thighs.",
    "Wide curvy hips balancing an oversized hanging belly.",
    "Fat obese body with gut pooling outward, thick thighs beneath.",
    "Overweight torso bending under a round sagging stomach.",
    "Deep belly creases stacked along a soft heavy torso.",
    "Plus-size figure with thick arms and a drooping gut.",
    "Soft body with wide hips carrying a hanging stomach.",
    "Fat-laden torso resting its gut deep over thighs.",
    "Heavy plush arms paired with a low sagging belly.",
    "Curvy obese woman thick with gut rolls and heavy hips.",
    "Immense body marked by gut sloping down into folds.",
    "Large soft figure with gut folds deep and pressing downward.",
    "Thick voluptuous body shaped by sagging belly and plush arms.",
    "Round fat torso heavy with overlapping gut layers.",
    "Plump hips rounding under a full hanging stomach.",
    "Stacked stomach folds rolling across wide thighs.",
    "Heavy bloated gut dominating a thick soft frame.",
    "Full-set obese body with belly folds pushing low.",
    "Massive hanging belly curving out over wide hips.",
    "Overloaded frame with gut spilling heavy across lap.",
    "Deep plush rolls layered along sagging stomach.",
    "Obese torso heavy with rounded belly bulging forward.",
    "Soft rounded gut creasing into multiple belly folds.",
    "Fat-packed hips supporting an oversized stomach.",
    "Wide frame stacked with gut folds and soft limbs.",
    "Heavy sagging belly resting deep between thick thighs.",
    "Low drooping gut pressing against plush thighs.",
    "Overfed figure weighed down by deep hanging folds.",
    "Heavyset torso bending with the weight of belly rolls.",
    "Bloated stomach hanging far over soft round hips.",
    "Wide belly folds creasing down into plump thighs.",
    "Immense torso bulging under layers of soft fat.",
    "Soft oversized gut folded heavy onto thighs.",
    "Deep set folds rolling across the sagging belly.",
    "Massive figure bending with heavy stomach layers.",
    "Round gut pulling downward past wide thick hips.",
    "Plush thighs supporting a sloping sagging belly.",
    "Stomach folds hanging heavy under full soft chest.",
    "Overfed obese body packed thick with belly weight.",
    "Heavy-set obese figure curved with deep gut rolls.",
    "Fat-laden torso sloping wide into plush hips.",
    "Bulging stomach layered with thick soft folds.",
    "Low resting gut pressing down on plump legs.",
    "Wide hips sprawling under a sagging stomach.",
    "Deep plush creases stacked along a soft belly.",
    "Bloated torso heavy with overlapping gut layers.",
    "Heavy arms framing a massive sagging stomach.",
    "Immense gut folds sloping into wide curvy hips.",
    "Thick rounded stomach pressing deep into thighs.",
    "Soft obese frame draped with heavy gut rolls.",
    "Massive belly folding thickly down into lap.",
    "Plush wide hips carrying a dense hanging gut.",
    "Bloated round belly stretched over plush thighs.",
    "Heavy-set obese body layered with thick folds.",
    "Massive torso softened by deep plush stomach rolls.",
    "Full curvy hips balancing a sagging gut forward.",
    "Fat-packed body folding downward with gut mass.",
    "Low sloping stomach creasing into wide thighs.",
    "Round bloated torso crowned with heavy gut layers.",
    "Stacked stomach folds sitting heavy above lap.",
    "Thick plush body anchored by a sagging belly mass.",
    "Deep curving gut folding low across hips and thighs.",
    "Fat-laden limbs framing a full drooping stomach.",
    "Overfed body with a massive hanging gut and round wide hips.",
    "Large fat figure with hanging belly and a curvy heavy torso.",
    "Massive soft belly spilling downward, thick thighs underneath.",
    "Obese heavyset figure with plush arms and sagging stomach folds.",
    "Curvy oversized woman with gut bulging forward and hips spreading wide.",
    "Round obese body with belly drooping heavily toward thighs.",
    "Fat figure with overhanging stomach and soft thick arms.",
    "Large plus-size body with plush thighs and belly folds pressing together.",
    "Huge round stomach layered with folds and resting on thighs.",
    "Soft hanging belly spilling forward over thick plump legs.",
    "Oversized belly folding into deep rolls, hips heavy and wide.",
    "Wide curvy hips paired with a massive soft belly and thick thighs.",
    "Heavy plump body with a round sagging stomach and plush arms.",
    "Thick voluptuous figure with gut pooling forward, thighs pressing inward.",
    "Immense obese woman with belly folds stacked low and hips dominating.",
    "Huge body with a bloated gut draping toward knees and arms soft.",
    "Massive torso weighted with belly rolls, hips curved and heavy.",
    "Ultra-fat figure with gut spilling heavily over thighs.",
    "Large hanging stomach pressing down with multiple soft folds.",
    "Heavyset plus-size figure with plush thighs and a drooping gut.",
    "Obese woman with belly creases gathered low above knees.",
    "Round full-bodied figure with plush hips and thick thighs.",
    "Super fat figure with gut sagging forward and arms layered with softness.",
    "Overweight body with a low hanging stomach and hips sprawling wide.",
    "Huge heavy figure with rolls lining a sagging stomach.",
    "Full-bodied obese woman with deep belly folds and thick thighs.",
    "Fat figure with a swollen gut and hips rolling into plump legs.",
    "Round curvy frame with wide hips, soft belly, and plush arms.",
    "Large fat female body with gut resting low and arms thick and smooth.",
    "Immense heavy body with rolls along belly and thighs thickly pressed.",
    "Deep belly creases stacking under a broad heavy torso.",
    "Wide hips carrying a soft sagging stomach downward.",
    "Bulging gut folding deeply as it presses into thick thighs.",
    "Plush thighs supporting a massive sagging stomach.",
    "Overweight torso heavy with gut folds and hips sprawling outward.",
    "Round curvy body with soft sagging arms and belly folds pooling.",
    "Fat plus-size figure with belly resting deep into lap.",
    "Heavy obese body layered with plush folds and soft limbs.",
    "Round wide frame marked by a sagging gut and plump hips.",
    "Obese figure with plush soft arms and a gut arching forward.",
    "Stacked belly rolls hanging over broad curvy hips.",
    "Soft plush limbs framing a massive hanging stomach.",
    "Heavyset round figure thick through hips and thighs.",
    "Layered belly folds cascading down onto thick legs.",
    "Enormous fat woman with sagging gut and hips spreading wide.",
    "Heavy round gut folding tightly into thick thighs.",
    "Drooping stomach creased heavily under full heavy breasts.",
    "Immense plus-size body soft and draped in gut folds.",
    "Round belly pressing outward as thick arms frame torso.",
    "Fat-laden hips supporting a gut pooling down into lap.",
    "Large body weighted by deep folds and sprawling thighs.",
    "Soft wide frame sloping into plush thighs and sagging gut.",
    "Massive torso bending under the pull of heavy stomach.",
    "Huge belly folds piling downward over curving hips.",
    "Plush arms rounding out a figure dominated by gut mass.",
    "Fat female figure curved with soft arms and sagging belly.",
    "Full heavyset body rich in gut rolls and thigh thickness.",
    "Stacked sagging folds pressed low between plump legs.",
    "Heavy belly draped with softness against thick plush thighs.",
    "Soft stretched gut anchoring a full-bodied obese frame.",
    "Overloaded torso crowned with sagging stomach layers.",
    "Dense fat body, gut bulging, hips flared, arms soft.",
    "Hanging belly mass rippling over plush thighs.",
    "Massive gut curving deep as hips spread outward.",
    "Obese curvy figure burdened with sagging stomach rolls.",
    "Soft figure where hips and gut dominate thick limbs.",
    "Heavy hanging gut drawn into broad plump folds.",
    "Thick soft body set heavy in belly and plush hips.",
    "Plush sagging gut pooling between thick legs.",
    "Dense belly folds running low toward knees.",
    "Round hips cushioning a weighty sagging gut.",
    "Body wide and low, heavy with soft hanging belly.",
    "Plump arms completing a mass of soft rolling folds.",
    "Thick folds tucking under the weight of gut spill.",
    "Heavy plush torso resting its mass on spreading thighs.",
    "Belly sloped wide and round over full-set hips.",
    "Massive round figure cradling its gut in plush thighs.",
    # Spicy Variations (10%)
    "Overfed obese body stuffed full, gut hanging heavy over thighs.",
    "Gluttonous fat woman with belly distended and rolling low.",
    "Overindulged body swollen with food, gut spilling outward.",
    "Heavyset feeder belly bulging proudly, hips sprawled thick.",
    "Stuffed gut pressing into plush thighs, soft folds creasing deep.",
    "Massive belly tight and sagging, arms soft from indulgence.",
    "Full bloated gut curving heavy under wide hips and thick legs.",
    "Obese stuffed body with gut folds pressed forward and thick limbs.",
    "Huge gluttonous belly sloping down across bloated thighs.",
    "Overfed fat figure laden with weight, gut heavy with fullness."
]

# Safety check
if len(CAPTIONS) < 166:
    raise ValueError(f"Not enough captions! Found {len(CAPTIONS)}")

def apply_captions(images_dir, captions):
    image_files = sorted([f for f in os.listdir(images_dir) if f.lower().endswith(('.jpg', '.jpeg', '.png'))])
    if len(image_files) != 166:
        print(f"⚠️ Found {len(image_files)} images, but expected 166.")
    for idx, img_file in enumerate(image_files):
        caption = captions[idx % len(captions)]
        txt_filename = os.path.splitext(img_file)[0] + ".txt"
        txt_path = os.path.join(images_dir, txt_filename)
        with open(txt_path, "w", encoding="utf-8") as f:
            f.write(caption)
        print(f"✅ {img_file} → {caption}")

if __name__ == "__main__":
    apply_captions(IMAGES_DIR, CAPTIONS)
    print("\n✅ All captions applied successfully. Your dataset is kohya-ready!")
